import Head from 'next/head';

import { Header } from '../components/Header';
import { Hero } from '../components/Hero';
import { About } from '../components/About';
import { Artists } from '../components/Artists';
import { Programming } from '../components/Programming';
import { Pricing } from '../components/Pricing';
import { Sponsors } from '../components/Sponsors';
import { Gallery } from '../components/Gallery';
import { Contact } from '../components/Contact';
import { Footer } from '../components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main>
        <Header />
        <Hero />
        <About />
        <Artists />
        {/* <Programming /> */}
        <Pricing />
        <Sponsors />
        {/* <Gallery /> */}
        {/* <Contact /> */}
        <Footer />
      </main>
    </>
  );
}
