export const sponsors = [
  {
    name: 'google',
    image: '/images/sponsors/google.webp',
    width: 170,
    height: 55.49,
    href: '',
  },
  {
    name: 'microsoft',
    image: '/images/sponsors/microsoft.webp',
    width: 170,
    height: 36.31,
    href: '',
  },
  {
    name: 'airbnb',
    image: '/images/sponsors/airbnb.webp',
    width: 170,
    height: 53.04,
    href: '',
  },
  {
    name: 'axure',
    image: '/images/sponsors/axure.webp',
    width: 170,
    height: 48.48,
    href: '',
  },
  {
    name: 'apple',
    image: '/images/sponsors/apple.webp',
    width: 170,
    height: 58.13,
    href: '',
  },
  {
    name: 'facebook',
    image: '/images/sponsors/facebook.webp',
    width: 170,
    height: 33.7,
    href: '',
  },
  {
    name: 'nokia',
    image: '/images/sponsors/nokia.webp',
    width: 170,
    height: 28.63,
    href: '',
  },
  {
    name: 'oracle',
    image: '/images/sponsors/oracle.webp',
    width: 170,
    height: 22.24,
    href: '',
  },
];
